#!/bin/sh
#
# compile for intel ifort
#
set -x
prog=$1

LIB="-L/u/Wesley.Ebisuzaki/home/grib2.v3.0.0.intel/lib -lwgrib2 -lgfortran -ldl -lz -lm"
MOD="-I/u/Wesley.Ebisuzaki/home/grib2.v3.0.0.intel/lib"
ifort -no-wrap-margin -qopenmp -o $prog $prog.f90 ${MOD} ${LIB} 
exit
