#!/bin/sh
#

module purge

module load envvar/1.0
module load PrgEnv-intel/8.1.0
module load craype/2.7.13
module load intel/19.1.3.304

module load wgrib2/2.0.8

make -f Makefile clobber
make -f Makefile

make -f Makefile2 clobber
make -f Makefile2


